### ISSUE TITLE
[BUG] 502 Bad Gateway after "Login with Spotify" prompt

### ISSUE THREAD

**Issue by Vinylwalk3r** [linuxserver/docker-your_spotify#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to login and linking my Spotify account to Your_Spotify docker container gives "502 Bad Gateway nginx" error message

### Expected Behavior

Spotify login page should load and allow me to login and link my Spotify account to Your_Spotify docker container.

### Steps To Reproduce

1. Run Unraid
2. Install "Your Spotify" (from here refered to as YS) docker by linuxserver.io and MongoDB official docker image using GUI
3. Configure YS to use "bridged" network
4. Change ports from 80 -> 280 and 443 -> 2443
5. Set APP_URL as the server IP of followed by 280 as such: http://192.168.1.x:280
6. Set WebUI as APP_URL
7. Start containers and go to WebUI
8. Try to login to Spotify
9. 502 Bad Gateway Nginx

### Environment

```markdown
- OS: Unraid 6.11.5
- How docker service was installed: Via Unraids GUI, I dont know more about the underlying tech to explain what it does under the hood.
```

### CPU architecture

x86-64

### Docker creation

```bash
Imgur link to GUI conf
https://imgur.com/a/G5YHPjE
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] 02-default-location: executing...
[migrations] 02-default-location: succeeded
[migrations] done

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
your_spotify: https://github.com/sponsors/Yooooomi

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

Setting resolver to  192.168.1.1
Setting worker_processes to 8
generating self-signed keys in /config/keys, you can replace these with your own keys if required
....+.................+...+.+..............+.......+......+.....+...+......+.............+...+.....+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*......+....+...+..+...+.......+...+........+.+......+..+.......+.....+.........+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..............+.......+...+.....+....+.....+.+..+.........+......+...+.+........+.............+....................+...+............+.......+......+..+...+....+..+....+...............+..+.......+........+..........+..+.+.....+.+.....+..........+...+............+......+.....+...+......+..........+........+.+..+....+...........+.......+...+..+.+.....+.+...........+....+........+......+.+..................+...+..+................+..+....+.........+...........+.+..............+.........................+.....+.+...+.........+...+..+.+..+....+...+..+....+.................+...+.+...+..+.........+.+........+...+....+...+...+..+.......+......+.....+...+.........+...+............+.............+........+......+...+...............+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.......+.+....................+......+...+.............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*......+...+............+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.......+..+..........+..+.+.........+.....+...+....+...+...+..+.+...........+.+.........+.........+.........+.....+.............+............+...+..+.......+.....+..........+...........+....+.....+....+.....+.+......+.........+.....+......+.............+.........+........+.......+...........+.+...+......+..+...+......+..........+........+...+...+.+.....+.+.............................+...+.......+..............+.+......+..+.............+..+.+.....+.........+.+..+.......+..+..........+...+........+.............+......+...........+....+........+.......+...+......+..............+.+..+..........+..+......+.+.....+.+...............+..............+...+.+.....+............+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
Setting API Endpoint to 'http://192.168.1.23:280/api'
[custom-init] No custom files found, skipping...
yarn run v1.22.19
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/www/server/node_modules/mongoose/lib/connection.js:824
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Connection.openUri (/app/www/server/node_modules/mongoose/lib/connection.js:824:32)
    at /app/www/server/node_modules/mongoose/lib/index.js:381:10
    at /app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/app/www/server/node_modules/mongoose/lib/index.js:1234:10)
    at Mongoose.connect (/app/www/server/node_modules/mongoose/lib/index.js:380:20)
    at /app/www/server/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/www/server/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 102927729,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:387:20)
            at Socket.<anonymous> (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:310:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node lib/bin/www
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/www/server/node_modules/mongoose/lib/connection.js:824
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Connection.openUri (/app/www/server/node_modules/mongoose/lib/connection.js:824:32)
    at /app/www/server/node_modules/mongoose/lib/index.js:381:10
    at /app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/app/www/server/node_modules/mongoose/lib/index.js:1234:10)
    at Mongoose.connect (/app/www/server/node_modules/mongoose/lib/index.js:380:20)
    at /app/www/server/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/www/server/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 102958743,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:387:20)
            at Socket.<anonymous> (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:310:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/www/server/node_modules/mongoose/lib/connection.js:824
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Connection.openUri (/app/www/server/node_modules/mongoose/lib/connection.js:824:32)
    at /app/www/server/node_modules/mongoose/lib/index.js:381:10
    at /app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/app/www/server/node_modules/mongoose/lib/index.js:1234:10)
    at Mongoose.connect (/app/www/server/node_modules/mongoose/lib/index.js:380:20)
    at /app/www/server/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/www/server/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 102989493,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:387:20)
            at Socket.<anonymous> (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:310:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node lib/bin/www
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/www/server/node_modules/mongoose/lib/connection.js:824
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Connection.openUri (/app/www/server/node_modules/mongoose/lib/connection.js:824:32)
    at /app/www/server/node_modules/mongoose/lib/index.js:381:10
    at /app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/app/www/server/node_modules/mongoose/lib/index.js:1234:10)
    at Mongoose.connect (/app/www/server/node_modules/mongoose/lib/index.js:380:20)
    at /app/www/server/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/www/server/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 103020507,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:387:20)
            at Socket.<anonymous> (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:310:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/www/server/node_modules/mongoose/lib/connection.js:824
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Connection.openUri (/app/www/server/node_modules/mongoose/lib/connection.js:824:32)
    at /app/www/server/node_modules/mongoose/lib/index.js:381:10
    at /app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/app/www/server/node_modules/mongoose/lib/index.js:1234:10)
    at Mongoose.connect (/app/www/server/node_modules/mongoose/lib/index.js:380:20)
    at /app/www/server/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/www/server/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 103051280,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:387:20)
            at Socket.<anonymous> (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:310:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node lib/bin/www
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/www/server/node_modules/mongoose/lib/connection.js:824
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Connection.openUri (/app/www/server/node_modules/mongoose/lib/connection.js:824:32)
    at /app/www/server/node_modules/mongoose/lib/index.js:381:10
    at /app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/app/www/server/node_modules/mongoose/lib/index.js:1234:10)
    at Mongoose.connect (/app/www/server/node_modules/mongoose/lib/index.js:380:20)
    at /app/www/server/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/www/server/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 103082257,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:387:20)
            at Socket.<anonymous> (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:310:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/www/server/node_modules/mongoose/lib/connection.js:824
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Connection.openUri (/app/www/server/node_modules/mongoose/lib/connection.js:824:32)
    at /app/www/server/node_modules/mongoose/lib/index.js:381:10
    at /app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/app/www/server/node_modules/mongoose/lib/index.js:1234:10)
    at Mongoose.connect (/app/www/server/node_modules/mongoose/lib/index.js:380:20)
    at /app/www/server/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/www/server/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 103113043,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:387:20)
            at Socket.<anonymous> (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:310:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node lib/bin/www
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/www/server/node_modules/mongoose/lib/connection.js:824
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
    at Connection.openUri (/app/www/server/node_modules/mongoose/lib/connection.js:824:32)
    at /app/www/server/node_modules/mongoose/lib/index.js:381:10
    at /app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/app/www/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/app/www/server/node_modules/mongoose/lib/index.js:1234:10)
    at Mongoose.connect (/app/www/server/node_modules/mongoose/lib/index.js:380:20)
    at /app/www/server/lib/database/index.js:39:49
    at Generator.next (<anonymous>)
    at /app/www/server/lib/database/index.js:22:71 {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'mongo:27017' => ServerDescription {
        address: 'mongo:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 103144047,
        lastWriteDate: 0,
        error: MongoNetworkError: getaddrinfo ENOTFOUND mongo
            at connectionFailureError (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:387:20)
            at Socket.<anonymous> (/app/www/server/node_modules/mongodb/lib/cmap/connect.js:310:22)
            at Object.onceWrapper (node:events:628:26)
            at Socket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: null,
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node ./lib/migrations.js
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
```

**Comment by thespad** [comment]
Your container can't connect to the database
```
[info]  Trying to connect to database at mongodb://mongo:27017/your_spotify
/app/www/server/node_modules/mongoose/lib/connection.js:824
  const serverSelectionError = new ServerSelectionError();

MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
```
As per the readme, you need a mongo database running either in another container or on the host for it to connect to. I appreciate Unraid does a terrible job of surfacing this stuff.

**Comment by JGNi** [comment]
> I appreciate Unraid does a terrible job of surfacing this stuff.

But also the developer should be a little more clear maybe.

**Comment by j0nnymoe** [comment]
@JGNi You want us to be more clear about an error that's already being displayed by the application that we just package into a container?

**Comment by JGNi** [comment]
![image](https://user-images.githubusercontent.com/26222087/218551861-5c6fc83f-02c6-4717-9f8a-d52771e86a98.png)
![image](https://user-images.githubusercontent.com/26222087/218551962-45e18a57-60ba-4966-b58c-2099c21dfe44.png)

I know have this. Shall the DB be created beforehand, or will the application do it?

**Comment by JGNi** [comment]
![image](https://user-images.githubusercontent.com/26222087/218552154-74294966-bee1-4a69-b888-653c399a3b89.png)

**Comment by JGNi** [comment]
![image](https://user-images.githubusercontent.com/26222087/218552333-6033054e-7375-4da9-a91c-b855573aff3e.png)

**Comment by JGNi** [comment]
> @JGNi You want us to be more clear about an error that's already being displayed by the application that we just package into a container?

Maybe more clear about the setup process?

**Comment by thespad** [comment]
The readme is clear about the need for a database and what is supported, we don't have any control over the fact that Unraid chooses not to surface it in its UI.

Assuming that a database is present and correctly configured, the container will automatically populate it.

**Comment by exocet12** [comment]
I am running into the same error as the OP and @JGNi. I have a mongo database, and do not receive the looking for DB errors in the original post - but that is not the OP's issue. The issue is that the container is unable to auth with Spotify (resulting in the Nginx 502 or 404 error that JGNi posted).

**Comment by exocet12** [comment]
To close the loop on my above issue (thanks to driz on the linuxserver discord). I entered the external (public) URL of my your_spotify container as the APP_URL, and that worked.  That allowed the container to reach Spotify.  Clearing the cache in your browser before testing may be necessary.

**Comment by JGNi** [comment]
> To close the loop on my above issue (thanks to driz on the linuxserver discord): I entered the external URL for your_spotify in the APP_URL parameter (rather than the container IP or localhost), as well as clearing the cache in my browser - that allowed the container to reach Spotify.

Can you point me to that conversation on discord?
What's an external URL? One on your public IP?

**Comment by JGNi** [comment]
https://discord.com/channels/354974912613449730/1075221918896111676
Found it

**Comment by exocet12** [comment]
Correct. I entered the external (public) URL of my your_spotify container as the APP_URL, and that worked. I will edit my above post for clarity.
